### ISSUE TITLE
[Question]: Utilizing this plugin with a managed workflow

### ISSUE THREAD

**Issue by mvolonnino** [GSTJ/react-native-code-push-plugin#1]
@GSTJ - Hello Again! I figured this would be more suitable place for this question - I am out of my comfort zone on this, and new to Expo's ecosystem.

Currently I am utilizing this plugin with a managed workflow. Everything is set up per this repo's readme, and the following SDK setup through the `codepush` documentation.

* I did also read through the documentation you replied to me in the other repo: https://docs.expo.dev/workflow/continuous-native-generation/

I read through that and am a little confused on the `CNG` and the benefits we get when we have a managed workflow? I though the benefits from using Expo and its managed workflow came from now having to deal with the `ios` and `android` folders, and needing to have Xcode & Android studio etc.

Like i stated in the other thread that we were talking on, my work wants to switch from the bare RN app we currently have to a managed Expo app to have a much easier development flow (currently very hard to onboard the bare RN app from the steps needed & to keep it up date) so i am trying not to `expo eject` and keep it managed, utilizing the `eas build` commands.

---

To test the codepush implementation, I have build profiles setup under the `eas.json` which can basically build `adhoc` internal testing preview builds for our different environments. When trying to test the implementation and updating my latest preview build that has the new config plugin added, i am running into a couple complications.

Im utilizing this command now to test out the codepush implementation:
```
"update:staging:ios": "appcenter codepush release-react -a org/App -d Staging -e index.tsx",
"update:staging:android": "appcenter codepush release-react -a org/App-1 -d Staging -e index.tsx",
 "update:staging:all": "yarn run update:staging:ios && yarn run update:staging:android"
```

My project is setup with Expo sdk 49 & Expo Router - which is utilizing an `index.tsx` file, without the `-e index.tsx` at the end of the commands, I was getting this error:
![Screenshot 2023-12-20 at 3 27 10 PM](https://github.com/GSTJ/react-native-code-push-plugin/assets/67405221/16ee2b09-3a34-451b-942e-6c2ba565093c)

Now - running the `yarn update:staging:all` command -  the next error I am stuck at is:

> "Unable to find either of the following plist files in order to infer your app's binary version: "ios/player-app/Info.plist", "ios/Info.plist". If your plist has a different name, or is located in a different directory, consider using either the "--plist-file" or "--plist-file-prefix" parameters to help inform the CLI how to find it."

I think this makes sense since the project is still a managed workflow, and I do not have access to the `ios/` `or android/ ` folders

Is there currently a workaround for this or does this plugin not take in effect a managed workflow? Or am I missing something as simple as running the `expo prebuild` command before running a codepush update?

Again, sorry for bothering you, you have already helped me out so much but this is one of the last straws needed for completing the project and being fully on the expo ecosystem and deploying it as our production app! So thank you so much for the time you already spent helping me in the other thread and I look forward to your response and getting this sorted out!

**Comment by GSTJ** [comment]
You need IOS/Android folders to use plugins (just run `expo prebuild --clean`). Every plugin needs it, as plugins change the Android and iOS folders for you.

You cannot use the Expo App while testing after this. However, this does not diminish the benefit of the expo too much - it will still be very easy to upgrade react native and keep stuff organized. You don't even need to commit those folders to git; they are generated on EAS Build automatically as default.

https://docs.expo.dev/config-plugins/introduction/

The `info.plist` error you got is normal and related to Codepush's CLI, not this project. You need to pass `--plist-file` with the path as it asks.

**Comment by mvolonnino** [comment]
Okay sorry, I am not using Expo Go, and utilizing the expo dev client as I have other plugins that I am using as well (namely Firebase a big one, but a couple others that required their own plugins.)

I have not had to run `expo prebuild` before, but have run the `eas build` command to generate the new app bundles when adding the new plugins and making the app.config changes, etc -  for me to then download and install (whether that be for simulator development or internal adhoc distro to run the dev client on my device). Currently everything is working when creating that build through `eas build`.

Now would I need to specifically run the `expo prebuild` like you suggested? (which after installing and hooking up this plugin I ran the `eas build` command to get new builds that had that installed in the app bundle already for running the `expo-dev-client` - again for clarity, the other plugins I have not had to run `expo prebuild`, and have just been able to create a new `eas build` and install that for the `expo-dev-client`.


As a quick workaround for the plist issue as right now like I stated, I do not have access to the native `ios` and `android` folders, i utilized the `-t` command at the end:

```
appcenter codepush release-react -a org/App -d Staging -e index.tsx -t 2.2.1
```

just to see if i could get something working - but then got this error as well which I am currently working through right now:

> node node_modules/.bin/react-native bundle --assets-dest /var/folders/6c/18wgk0yx1y38yc747lq9_9l00000gn/T/code-push20231120-39645-1gdqr8n.qs2x/CodePush --bundle-output /var/folders/6c/18wgk0yx1y38yc747lq9_9l00000gn/T/code-push20231120-39645-1gdqr8n.qs2x/CodePush/main.jsbundle --dev false --entry-file index.tsx --platform ios
error No Metro config found in /Users/mattvolonnino/Desktop/volosports/player-app.
Error: Failed to release a CodePush update.

the big part there is the `No Metro config found` which I do not have a `metro.config.js` since I am using the Expo Router initial setup.

**Comment by GSTJ** [comment]
You need to run prebuild; EAS Build did this for you, and that's why you had no issues in the past.

You can opt to not commit those changes if you want (no IOS and Android folders), but you need to run it as you are not publishing on CI (where they are currently being generated)

**Comment by mgscreativa** [comment]
Hi! I confirm the plugin works in my demo Expo managed project! https://github.com/mgscreativa/react-native-code-push-expo-plugin-managed-workflow

https://github.com/GSTJ/react-native-code-push-plugin/assets/1286632/a07cc672-5a57-4024-8c43-6ab42103f212
