### ISSUE TITLE
Prepare for standalone Code Push Server instances

### ISSUE THREAD

**Issue by mgscreativa** [GSTJ/react-native-code-push-plugin#10]
Hi! as described in the CP project readme it needs to have set up some config keys to set the stand alone server URL as stated here https://github.com/microsoft/code-push-server/blob/main/api/README.md#configure-react-native-code-push

So I think this plugin needs to expose those config values in order to be set up in the Expo project config

**Comment by GSTJ** [comment]
Hey! It should be straightforward. I won't be able to look into it this week but feel free to open a PR, and I'll review it if you can.

We can accept a `serverUrl` on the plugin configs and replace the `plist` and `strings` entries if there's one.

**Comment by mgscreativa** [comment]
Done, please double check my PR because I didn't tested it, but I think all seems right
