### ISSUE TITLE
[README] Update README - install

### ISSUE THREAD

**Issue by mvolonnino** [GSTJ/react-native-code-push-plugin#2]
This is not really an issue but just wanted to make it aware in case anyone else i having the same issues I faced, or if they are migrating from utilizing `eas-updates` to `codepush`

Make sure to completely remove the `expo-updates` package from package.json if you utilized that before integrating this `codepush` plugin
_There will be no warnings or anything like that and everything will seem to work as intended._

I was running into two specific issues:

- iOS: everything worked as expected, and would download and even install the update correctly. But upon a force quit, the app would rollback and the `codepush` bundle would no longer be shown, but rather the bundle that was downloaded along with the App itself.

- Android: was getting the error below and it would never even fully download/install the bundle at all (`codePush.sync()` would not work either, or using `codePush.checkForUpdates()` and downloading manually would not work either)
>'Update is invalid - a JS bundle file named "null" could not be found within the downloaded contents'

---

After completely remove the `expo-updates` with 
```
yarn remove expo-updates
```

and removing the below code from the app.json, then this plugin worked correctly and I have no issues on `iOS` or `android`
_this had to deal with hooking up `eas updates` and completely removing that along with removing package seems to have work_
```
// filename: app.json

{
  "expo": {
       //...
       updates: {}, // remove this
}
```

Huge shoutout to @GSTJ for creating this plugin and to @mgscreativa for helping debug as well and finding the solution to those issues I was running into above.

**Comment by mgscreativa** [comment]
Hi @GSTJ, just created a PR to update the readme

**Comment by GSTJ** [comment]
Updated, thanks guys! Good find there.
